### ISSUE TITLE
slice bounds out of range [:4380] with capacity 4096

### ISSUE THREAD

**Issue by Rid-lin** [go-routeros/routeros#19]
Good day.
When using this library, an error occurs:

```
panic: runtime error: slice bounds out of range [:4380] with capacity 4096

goroutine 11 [running]:
bufio.(*Reader).Read(0xc0000556e0, 0xc0028c6a4e, 0x1, 0x1, 0x0, 0x0, 0x0)
        C:/Go/src/bufio/bufio.go:238 +0x3da
io.ReadAtLeast(0xa1da20, 0xc0000065b8, 0xc0028c6a4e, 0x1, 0x1, 0x1, 0x9, 0x1acac200a28, 0x30)
        C:/Go/src/io/io.go:328 +0x8e
io.ReadFull(...)
        C:/Go/src/io/io.go:347
gopkg.in/routeros.v2/proto.(*reader).readNumber(0xc0000065b8, 0x1, 0x5321d8, 0x100000000000030, 0x1acd1a77e68)
        C:/Users/root/go/src/github.com/rid-lin/gomtc/vendor/gopkg.in/routeros.v2/proto/reader.go:62 +0x85
gopkg.in/routeros.v2/proto.(*reader).readLength(0xc0000065b8, 0xc0028c6a40, 0x9, 0xc000046c01)
        C:/Users/root/go/src/github.com/rid-lin/gomtc/vendor/gopkg.in/routeros.v2/proto/reader.go:74 +0x3f
gopkg.in/routeros.v2/proto.(*reader).readWord(0xc0000065b8, 0xc001b096e0, 0xc0028c6a40, 0x9, 0xc00329c1c8, 0x1)
        C:/Users/root/go/src/github.com/rid-lin/gomtc/vendor/gopkg.in/routeros.v2/proto/reader.go:100 +0x36
gopkg.in/routeros.v2/proto.(*reader).ReadSentence(0xc0000065b8, 0xc001d64e20, 0x0, 0xcaa5c8)
        C:/Users/root/go/src/github.com/rid-lin/gomtc/vendor/gopkg.in/routeros.v2/proto/reader.go:28 +0x8f
gopkg.in/routeros%2ev2.(*Client).readReply(0xc000055740, 0x0, 0x0, 0xc0018ab5e0)
        C:/Users/root/go/src/github.com/rid-lin/gomtc/vendor/gopkg.in/routeros.v2/reply.go:29 +0x62
gopkg.in/routeros%2ev2.(*Client).endCommandSync(0xc000055740, 0xc0018ab5a0, 0x1d, 0x0)
        C:/Users/root/go/src/github.com/rid-lin/gomtc/vendor/gopkg.in/routeros.v2/run.go:42 +0x7c
gopkg.in/routeros%2ev2.(*Client).RunArgs(0xc000055740, 0xc0032298a0, 0x3, 0x3, 0xe, 0xc0018ab5a0, 0x1d)
        C:/Users/root/go/src/github.com/rid-lin/gomtc/vendor/gopkg.in/routeros.v2/run.go:26 +0x171
```
Good day.
When using this library, an error occurs:
What can you advise?

**Comment by andre-luiz-dos-santos** [comment]
What RouterOS command were you running when this error happened?

**Comment by Rid-lin** [comment]
*routeros.Client.Run("/ip/dhcp-server/lease/print") 
or
*routeros.Client.Run("/ip/dhcp-server/lease/printall")

**Comment by Rid-lin** [comment]
I put a `fmt.Print(response)` and sometimes got the wrong answer from microtik, where at first there was a lot of rubbish of a very long length. I assume this is due to an unstable connection.

**Comment by archaron** [comment]
I think, this needs a test that will "receive" a garbage data.
